const en = {
  'app-loginpage-title': 'Login',
  'app-loginpage-login-label': 'Login',
  'app-loginpage-login-placeholder': 'Enter your name',
  'app-loginpage-password-label': 'Password',
  'app-loginpage-password-placeholder': 'Enter your password',
  'app-loginpage-button-text': 'Login',
  'app-loginpage-question': 'Don\'t have an account?',
  'app-loginpage-suggestion': 'Go to the Registration page',
  'app-header-title': 'Movies',
  'app-header-logout-button': 'Logout',
  'app-header-logout-button-tip': 'Logout',
  'app-header-lang-button-tip': 'Site language',
  'app-mainpage-sort': 'Sort movies',
  'app-mainpage-sort-likes': 'Sort by likes',
  'app-mainpage-sort-rating': 'Sort by rating',
  'app-mainpage-sort-type-asc': 'ASC',
  'app-mainpage-sort-type-desc': 'DESC',
  'app-mainpage-search-placeholder': 'Search by name',
  'app-infopage-link-to-mainpage': 'Go to all movies',
  'app-infopage-produced-by': 'Produced by',
  'app-infopage-release': 'Release',
  'app-infopage-button-edit': 'Edit movie',
  'app-infopage-button-delete': 'Delete movie',
  'app-infopage-site': 'Site',
  'app-infopage-genres': 'Genres',
  'app-infopage-description': 'Description',
  'app-infopage-cast': 'Cast',
  'app-editpage': 'Edit Movie',
  'app-editpage-title': 'Title',
  'app-editpage-image': 'Image URL',
  'app-editpage-genres': 'Genres',
  'app-editpage-description': 'Description',
  'app-editpage-button-save': 'Save',
  'app-editpage-button-back': 'Go back',
  'app-editpage-title-placeholder': 'Enter title...',
  'app-editpage-image-placeholder': 'Enter imageUrl...',
  'app-editpage-genres-placeholder': 'Enter genres...',
  'app-editpage-description-placeholder': 'Enter description...',
};

export default en;
