const ua = {
  'app-loginpage-title': 'Будь ласка, авторизуйтесь',
  'app-loginpage-login-label': 'Логін',
  'app-loginpage-login-placeholder': 'Введіть свій логін',
  'app-loginpage-password-label': 'Пароль',
  'app-loginpage-password-placeholder': 'Введіть свій пароль',
  'app-loginpage-button-text': 'Авторизуватись',
  'app-loginpage-question': 'Не маєте акаунту?',
  'app-loginpage-suggestion': 'Зареєструватись.',
  'app-header-title': 'Фільми',
  'app-header-logout-button': 'Вийти',
  'app-header-logout-button-tip': 'Вийти',
  'app-header-lang-button-tip': 'Мова сайту',
  'app-mainpage-sort': 'Сортувати фільми',
  'app-mainpage-sort-likes': 'За лайками',
  'app-mainpage-sort-rating': 'За рейтингом',
  'app-mainpage-sort-type-asc': 'Від найбільшого',
  'app-mainpage-sort-type-desc': 'Від найменшого',
  'app-mainpage-search-placeholder': 'Шукати за назвою',
  'app-infopage-link-to-mainpage': 'До списку всіх фільмів',
  'app-infopage-produced-by': 'Створено компаниєю',
  'app-infopage-release': 'Реліз',
  'app-infopage-button-edit': 'Редагувати фільм',
  'app-infopage-button-delete': 'Видалити фільм',
  'app-infopage-site': 'Сайт',
  'app-infopage-genres': 'Жанри',
  'app-infopage-description': 'Огляд',
  'app-infopage-cast': 'Акторський склад',
  'app-editpage': 'Редагувати фільм',
  'app-editpage-title': 'Назва',
  'app-editpage-image': 'URL картинки',
  'app-editpage-genres': 'Жанри',
  'app-editpage-description': 'Короткий огляд',
  'app-editpage-button-save': 'Зберегти',
  'app-editpage-button-back': 'Відмінити',
  'app-editpage-title-placeholder': 'Введіть назву...',
  'app-editpage-image-placeholder': 'Введіть URL картинки...',
  'app-editpage-genres-placeholder': 'Введіть жанри через кому...',
  'app-editpage-description-placeholder': 'Введіть текст ...',
};

export default ua;
